---
- name: Prepare stage
  hosts: stage
  become: yes

  roles:
    - docker_prep
    - dockerhub_auth
    - boxfuse_building

- name: Prepare prod
  hosts: prod
  become: yes

  roles:
    - docker_prep
    - dockerhub_auth
    - boxfuse_container