---
- name: install app on stage(java, maven)
  hosts: build
  become: yes

  tasks:
  - name: Update all packages to their latest version
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure java is present
    apt:
     name: default-jdk
     state: present

  - name: Ensure maven is present
    apt:
     name: maven
     state: present

  - name: Ensure git is present
    apt:
     name: git
     state: present
  
  - name: Ensure rsync is present
    apt:
     name: rsync
     state: present

  - name: Ensure reository clone to host
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
     dest: /home/repo
     clone: yes
  
  - name: Change the working directory to somedir/ before executing the command.
    shell: mvn package
    args:
      chdir: /home/repo

- name: install app on prod (tomcat)
  hosts: prod
  become: yes

  tasks:
  - name: Update all packages to their latest version
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Ensure tomcat is present
    apt:
     name: tomcat9
     state: present
  
  - name: Ensure tomcat is started
    service:
     name: tomcat9
     state: started

  - name: Ensure rsync is present
    apt:
     name: rsync
     state: present

  - name: Copy war-file on prod
    synchronize:
     src: /home/repo/target/hello-1.0.war
     dest: /var/lib/tomcat9/webapps
    delegate_to: 35.228.96.73