---
# tasks file for dockerhub_auth
- name: Ensure host machine is authorized in DockerHub
  docker_login:
    email: '{{ dockerhub_email }}'
    username: "{{ dockerhub_user }}"
    password: "{{ dockerhub_token }}"