---
# tasks file for docker_prep
- name: Ensure docker is present
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure docker python is present
  apt:
    name: python-pip
    state: present
    update_cache: yes

- name: Ensure docker-py is present
  pip:
    name: docker-py
    state: present